spring.application.name=discovery-service
server.port=8761
# pour que DiscoveryService ne récupère pas le registre
eureka.client.fetch-registry=false
#discovery n a pas besoin de s enregistrer dans le registre
eureka.client.register-with-eureka=false